<a href="https://colab.research.google.com/github/Vonewman/Deep-Learning/blob/master/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor

In [1]:
import torch

In [2]:
x = torch.empty(1)
print(x)

tensor([-6.1065e+32])


In [3]:
x = torch.empty(3)
print(x)

tensor([-6.1067e+32,  3.0620e-41,  4.3440e-44])


In [4]:
x = torch.empty(2, 3)
print(x)

tensor([[-6.1067e+32,  3.0620e-41,  4.4842e-44],
        [ 0.0000e+00,         nan,  7.1228e-06]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

tensor([[[-6.1068e+32,  3.0620e-41,  4.4842e-44],
         [ 0.0000e+00,         nan,  7.1228e-06]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
tensor([[0.3309, 0.3500, 0.4189],
        [0.6253, 0.2672, 0.5506],
        [0.8368, 0.1617, 0.9544],
        [0.2757, 0.2194, 0.9923],
        [0.5924, 0.5935, 0.9271]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.Size([2])


### requires_grad argument

In [6]:
x = torch.tensor([5.5, 3], requires_grad=True)

### Operations on Tensors

In [11]:
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# subtraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

## Slicing

In [12]:

x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.5717, 0.7473, 0.6822],
        [0.9035, 0.4235, 0.0604],
        [0.8677, 0.1697, 0.1339],
        [0.8569, 0.9564, 0.1396],
        [0.4906, 0.5721, 0.1085]])
tensor([0.5717, 0.9035, 0.8677, 0.8569, 0.4906])
tensor([0.9035, 0.4235, 0.0604])
tensor(0.4235)
0.4235326647758484


### Reshape with `torch.view()`

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy

In [14]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### Move Tensors to GPU

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()